# Generated by Django 3.1.14 on 2023-07-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0011_auto_20230709_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonentity',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
