version: '3.8'

services:
  djangoapp:
    build:
      context: .
      args:
        dev: true
    command: python3 manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    ports:
      - 8080:8000
    volumes:
      - ./src:/app
      - ./data/db:/app/db
      - ./data/media:/app/media

networks:
  db_net:
    driver: bridge
